### ISSUE TITLE
Fatal error on empty template

### ISSUE THREAD

**Issue by Ilja-developer** [Indigo744/Modx-Revo-Simple-Ace-Code-Editor#13]
When I set a resource to an empty template I get the following error:

Fatal error: Uncaught Error: Call to a member function getTemplateVarList() on null in xx\core\cache\includes\elements\modplugin\9.include.cache.php:385 Stack trace: #0 xx\core\model\modx\modscript.class.php(70): include() #1 xx\core\model\modx\modx.class.php(1608): modScript->process() #2 xx\manager\controllers\default\resource\resource.class.php(160): modX->invokeEvent('OnDocFormPreren...', Array) #3 xx\core\model\modx\modmanagercontroller.class.php(158): ResourceManagerController->firePreRenderEvents() #4 xx\core\model\modx\modmanagerresponse.class.php(74): modManagerController->render() #5 xx\core\model\modx\modmanagerrequest.class.php(183): modManagerResponse->outputContent(Array) #6 xx\core\model\modx\modmanagerrequest.class.php(131): modManagerRequest->prepareResponse() #7 D:\Stack\2_Htd in xx\core\cache\includes\elements\modplugin\9.include.cache.php on line 385

When I disable the plugin the error does not occur.

**Comment by Ilja-developer** [comment]
> It is known (#12) and fixed ([1.5.1](https://github.com/Indigo744/Modx-Revo-Simple-Ace-Code-Editor/releases/tag/1.5.1-pl)).

Thanks so much :)
